### ISSUE TITLE
If device.ringAsync() is used, a default Jabra ringtone will be played

### ISSUE THREAD

**Issue by aabuhijleh** [gnaudio/jabra-node-sdk#17]
If we use `device.setHidWorkingStateAsync(enumHidState.GN_HID)` with Jabra Speak 510

And then we call `device.ringAsync()`

The device will ring properly and the LEDs will flash as required. However, there's an issue because a default Jabra ringtone will be played.

This behavior is undesired. We want to respect the ringtone the user chose in our application, and not use a random Jabra ringtone.

Is there a way to disable this behavior and not play a ringtone? Just flash the LEDs?

It appears this issue does not exist if we don't call `device.setHidWorkingStateAsync(enumHidState.GN_HID)`. However we have to do that in order to receive offhook events as mentioned in #3.

In the old SDK (v1), the default ringtone will also be played.

Thanks in advance.

### Code (How we add a call to the device):

```js
await this.device.onhookAsync();
if (incoming) {
    await this.device.ringAsync();
} else {
    await this.device.unringAsync();
}
await this.device.unmuteAsync();
```

**Comment by jabra-slawaetz** [comment]
Thanks for posting your question.
It is possible that there is a an issue with the ring functionality on the 510.
But we will need to investigate the issue before we can provide a qualified answer to this.

To provide you with structured support, we would like to ask you to register on developer.jabra.com so that we can track the issue with our support platform for such matters. Any resolution will also be shared with the developer community.

Thanks

**Comment by aabuhijleh** [comment]
Hi @jabra-slawaetz 

I've actually posted about this issue on the forums some time ago

Here's the post: https://developer.jabra.com/forums/posts/list/209.page
