### ISSUE TITLE
`getRCCStatus` is missing on device.

### ISSUE THREAD

**Issue by henrikbjorn** [gnaudio/jabra-node-sdk#2]
Can't seem to find another way of asking if the headset is ringing or not. Previously it could be done with `getRCCStatus().isRinging`

**Comment by extmchristensen** [comment]
Thanks for trying out the new beta! You need to maintain such state yourself as you call ringAsync(), unringAsync() etc. (if the promises succeed, change has been changed).

This is because the new npm is a pure wrapper for our native "c" sdk. Unlike the old version, it does not add extra business logic or try to maintain the additional state that getRCCStatus exposed (state which was not always correct anyway in the old npm).

**Comment by henrikbjorn** [comment]
Okay, thanks. Just saw some type called RCCStatus so assumed it was missing.
