### ISSUE TITLE
Managing multiple calls with Jabra devices

### ISSUE THREAD

**Issue by aabuhijleh** [gnaudio/jabra-node-sdk#20]
Hello guys,

Here's our use case:
* User with 2 softphone apps on the desktop
* Jabra device connected on the computer
* Jabra device detected by both apps

Is there a way to solve the following issue?
* Call 1 established on Softphone 1
* Call 2 is received on Softphone 2 ==> Pressing the Call Answer button on the device disconnects Call 1 ==> Call 1 shall not be disconnected in that context

Thanks in advance!

**Comment by jabra-slawaetz** [comment]
Hello, and happy new year.

If we understand you question correctly, you want to synchronise call-control on two separate softphones so that you can move what is the active call from one to the other.
In other words, with an activ call on SF1, and pressing the pick-up button to answer an incoming call on SF2 would put the call on SF1 on hold, and let SF2 control the headset until switching back somehow.

We don't support this specifically using the APIs. Jabra devices follow the USB HID specifications and behaviour closely, and the way this works does not really cater for multi-softpone call marshalling. (It's either one or the other in control.)

If you had control over the implementation in both softphones, and could create some inter-softphone communication, you might be able to implement this behaviour using a headset sharing mechanism, but using USB HID it would be difficult to achieve.

**Comment by aabuhijleh** [comment]
Thanks for the reply. I'll close this issue.
