### ISSUE TITLE
`btnPress` not registered for device when ringing

### ISSUE THREAD

**Issue by henrikbjorn** [gnaudio/jabra-node-sdk#3]
Testing the SDK with a Jabra Engage 75 it does not register the `btnPress` when trying to answer a call via the headset or base stattion. Rejecting the call works fine.

`btnPress` sends a `line busy` if the device is not ringing.

**Comment by henrikbjorn** [comment]
Here is a working test case

``` javascript
const { createJabraApplication, jabraEnums } = require('@gnaudio/jabra-node-sdk')

async function main() {
  const jabra = await createJabraApplication('asdasd')

  jabra.on('attach', device => {
    device.on('btnPress', (btnType, btnValue) => {
      const type = jabraEnums.enumDeviceBtnType[btnType]

     console.log(type)

      switch (type) {
        case 'RejectCall': {
          device.unringAsync()

          return
        }
      }
    })

    console.log('attached')
    device.ringAsync()
  })

  await jabra.scanForDevicesDoneAsync()
}


main()
```

**Comment by extmchristensen** [comment]
Thanks for the updated example - that makes it easier to see what is going on.

The new npm uses standard HID by default (not sure what the old one used) which is what Skype uses and which does not send hook off events. In order to receive hook off events in a custom softphone, you should switch to GN hid after initializing the library. Import enumHidState and add `device.setHidWorkingStateAsync(enumHidState.GN_HID)` on top of your attach handler and I expect it to work.

_All this protocol stuff is of cause not documented well enough from our side yet - sorry for that._

P.S. You can still - but don't have to - use jabraEnums anymore. You can also just import the individual enums as needed.

**Comment by aabuhijleh** [comment]
@extmchristensen 

If we use `device.setHidWorkingStateAsync(enumHidState.GN_HID)` with Jabra Speak 510

And then we call `device.ringAsync()`

The device will ring properly and the LEDs will flash as required. However, there's an issue because a default Jabra ringtone will be played.

This behavior is undesired. We want to respect the ringtone the user chose in our application, and not use a random Jabra ringtone.

Is there a way to disable this behavior and not play a ringtone? Just flash the LEDs?

It appears this issue does not exist if we don't call `device.setHidWorkingStateAsync(enumHidState.GN_HID)`. However we have to do that in order to receive offhook events

I would really appreciate your help in this matter.

**Comment by mmc41** [comment]
@aabuhijleh Please add a new issue for this.

**Comment by aabuhijleh** [comment]
Sure
